project:
  type: website
  output-dir: _site

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: Project/index.html
        text: Home
      - href: Project/about.html
        text: About
      - href: Project/projects.html
        text: Projects
      - href: Project/contact.html
        text: Contact Me
      

format:
  html:
    theme:
      - cosmo
      - brand
      - Project\custom.scss
    css: styles.css
    toc: true



