project:
  type: website
  output-dir: _site
  resources:
    - "Project/Perla_Keily_Resume.pdf"

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: Project/index.html
        text: Home
      - href: Project/about.html
        text: About Me
      - href: Project/projects.html
        text: Projects
      - href: Project/contact.html
        text: Contact
      

format:
  html:
    theme:
      - cosmo
      - brand
      - Project\custom.scss
    css: styles.css
    toc: true



