---
title: "About Me"
subtitle: Academic, Professional, and Volunteering Background
---

## Boston University
**Master of Science in Applied Business Analytics** - In Progress

My goal is to use the combination of my degrees as a bridge between business development and the engineering mindset to pursue my interest in process improvement and optimization.

## University of Connecticut
**Bachelor of Science in Engineering**

During my time at UConn I developed a strong foundation in fluid mechanics, process kinetics, thermodynamics, and air pollution control. I was able to simultaneously grow my passion for sustainable solutions.

## Straumann Group
**Quality Assurance Biotech Co-op**

I was lucky enough to find multiple mentors and helping hands during my time in quality assurance. I enjoyed my ability to collaborate with various departments and explore the different fields that my technical expertise could be applied to. 

## The Hole in the Wall Gang Camp
**Volunteering and Fundraising**

Since my junior year of college, I began to spend a lot of my spare time with the Hole in the Wall Gang Camp. It's a summer camp that provides “a different kind of healing" to children with serious illnesses and their families. I have the pleasure of meeting the kindest people from all different paths of life. Though I'm proud of all my accomplishments, the time I spend at camp is by far my proudest. 

